/**
 * GENERATED by scripts/generate-slot-fields.mjs — the fields each section
 * slot actually uses. The Studio hides the other (empty) fields of a section
 * so editors only see what the website renders.
 *
 * To expose a field for a slot, add its name here (or re-run the generator
 * after the field has content).
 */

export type SlotFieldLevels = {
  /** Fields on the section itself. */
  section: string[];
  /** Fields inside the section heading. */
  heading: string[];
  /** Fields on each card. */
  card: string[];
  /** Fields on entries nested inside cards. */
  cardEntry: string[];
  /** Fields on entries directly on the section. */
  entry: string[];
};

/** Keyed by "<page id>/<slot>". */
export const SLOT_FIELDS: Record<string, SlotFieldLevels> = {
  "about-page/accreditations": {
    "section": [
      "body",
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "about-page/adekSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "about-page/boardGovernors": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "image",
      "subtitle",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "about-page/branches": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "cta",
      "description",
      "image",
      "label",
      "subtitle",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "about-page/governance": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "about-page/inspection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "about-page/intro": {
    "section": [
      "body",
      "ctas",
      "image"
    ],
    "heading": [],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "about-page/ourStory": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "eyebrow",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "about-page/ourStoryFeature": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "about-page/principalMessage": {
    "section": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "about-page/statement": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "description",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "about-page/values": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "entries",
      "image",
      "title"
    ],
    "cardEntry": [
      "icon",
      "label",
      "text"
    ],
    "entry": []
  },
  "academics-elementary-page/assessmentDetailSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-elementary-page/assessmentSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-elementary-page/curriculumSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-elementary-page/dayInLifeSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-high-school-page/apBenefitsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "subtitle",
      "title"
    ],
    "card": [
      "description",
      "icon",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "academics-high-school-page/apDiplomaSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "eyebrow",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-high-school-page/careerGuidanceIntroSection": {
    "section": [
      "heading"
    ],
    "heading": [
      "subtitle",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-high-school-page/careerGuidanceSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-high-school-page/careerGuidanceSliderSection": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "description",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "academics-high-school-page/curriculumSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-high-school-page/dayInLifeSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-high-school-page/overviewSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-high-school-page/pathwaysSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-high-school-page/pathwaysSliderSection": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "description",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "academics-kindergarten-page/arabicPolicySection": {
    "section": [
      "ctas",
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-kindergarten-page/curriculumSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-kindergarten-page/dayInLifeSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-kindergarten-page/drdpSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "iconType",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "academics-kindergarten-page/excellenceSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-middle-school-page/assessmentDetailSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-middle-school-page/assessmentSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-middle-school-page/curriculumSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-middle-school-page/dayInLifeSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-middle-school-page/learningPhasesElementaryImage": {
    "section": [
      "image"
    ],
    "heading": [],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-middle-school-page/overviewSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-middle-school-page/supportProgramsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "description",
      "icon",
      "iconType",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "academics-page/assessmentProtocolSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "description",
      "icon",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "academics-page/curriculumSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-page/inclusionFeatureSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-page/inclusionSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-page/learningSliderSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "description",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "academics-page/steamSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "academics-page/supportProgramsSection": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "description",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "academics-page/teachingCommitmentsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "description",
      "iconType",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "admissions-application-page/applicationProcess": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "admissions-application-page/finalCta": {
    "section": [
      "ctas",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "admissions-application-page/mograHubAppBand": {
    "section": [
      "entries",
      "heading"
    ],
    "heading": [
      "description",
      "eyebrow",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": [
      "href",
      "iconType",
      "label",
      "text"
    ]
  },
  "admissions-application-page/stepsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "body",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "admissions-application-page/videoSection": {
    "section": [
      "image"
    ],
    "heading": [],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "admissions-book-tour-page/formSection": {
    "section": [
      "errorMessage",
      "recipientEmail",
      "submitLabel",
      "successMessage"
    ],
    "heading": [],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "admissions-book-tour-page/introSection": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "admissions-faq-page/faqSection": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "description",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "admissions-faq-page/introSection": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "admissions-fees-page/feeStructure": {
    "section": [
      "cards",
      "entries",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "entries",
      "title"
    ],
    "cardEntry": [
      "label",
      "text"
    ],
    "entry": [
      "label",
      "text"
    ]
  },
  "admissions-fees-page/journeySection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "admissions-fees-page/termsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "body",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "admissions-fees-page/termsSection.rightColumn": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "body",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "admissions-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "admissions-page/policySection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "admissions-register-interest-page/formSection": {
    "section": [
      "errorMessage",
      "recipientEmail",
      "submitLabel",
      "successMessage"
    ],
    "heading": [],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "admissions-register-interest-page/introSection": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "admissions-withdrawal-page/intro": {
    "section": [
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "admissions-withdrawal-page/stepsSection": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "body",
      "label",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "careers-page/careSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "careers-page/commitmentSection": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "description",
      "entries",
      "title"
    ],
    "cardEntry": [
      "text"
    ],
    "entry": []
  },
  "careers-page/intro": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "careers-page/joinTeamSection": {
    "section": [
      "entries",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": [
      "href",
      "icon",
      "label",
      "text"
    ]
  },
  "careers-page/requirementsSection": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "entries",
      "subtitle",
      "title"
    ],
    "cardEntry": [
      "text"
    ],
    "entry": []
  },
  "contact-page/contactInfo": {
    "section": [
      "body",
      "entries",
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": [
      "href",
      "iconType",
      "label",
      "text"
    ]
  },
  "extra-curricular-activities-page/enrichingSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "extra-curricular-activities-page/tourIntro": {
    "section": [
      "heading"
    ],
    "heading": [
      "accentTitle",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "food-services-nutrition-page/cafeteriaSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "food-services-nutrition-page/hygieneSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "food-services-nutrition-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "food-services-nutrition-page/teamSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "health-safety-page/approachSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "health-safety-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "homepage-main/accreditations": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "homepage-main/ctaBand": {
    "section": [
      "ctas",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "homepage-main/facts": {
    "section": [
      "entries",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": [
      "label",
      "text"
    ]
  },
  "homepage-main/growthFeature": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "homepage-main/growthSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "homepage-main/heroContactBand": {
    "section": [
      "ctas",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "homepage-main/instagram": {
    "section": [
      "ctas",
      "heading",
      "images"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "homepage-main/intro": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "homepage-main/learningPhases": {
    "section": [
      "cards",
      "cta",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "cta",
      "description",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "homepage-main/news": {
    "section": [
      "cta",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "homepage-main/quickLinks": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "cta",
      "description",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "homepage-main/tour": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "accentTitle",
      "description",
      "subtitle",
      "title"
    ],
    "card": [
      "cta",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "homepage-main/whySection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "medical-services-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "medical-services-page/servicesSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "medical-services-page/staffSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "news-listing-page/newsListing": {
    "section": [
      "cta",
      "heading"
    ],
    "heading": [
      "subtitle",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "our-campus-page/elementaryLibrarySection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "our-campus-page/facilities": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "our-campus-page/facilitiesGrid": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "description",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "our-campus-page/intro": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "our-campus-page/librarySection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "our-campus-page/videoSection": {
    "section": [
      "image"
    ],
    "heading": [],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "our-community-page/linksSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "cta",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "our-community-page/supportSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "our-team-page/leadershipSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "eyebrow",
      "title"
    ],
    "card": [
      "description",
      "image",
      "label",
      "subtitle",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "parent-involvement-page/communitySection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "parent-involvement-page/partnershipSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "parent-involvement-page/programSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "parent-involvement-page/videoSection": {
    "section": [
      "image"
    ],
    "heading": [],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "school-calendar-page/calendarDownload": {
    "section": [
      "ctas",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "school-calendar-page/intro": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "school-calendar-page/terms": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "entries",
      "title"
    ],
    "cardEntry": [
      "label",
      "text"
    ],
    "entry": []
  },
  "school-policies-page/intro": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "school-policies-page/policies": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "image",
      "label",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "school-reports-page/intro": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "school-supplies-uniform-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "school-supplies-uniform-page/uniformSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-inclusion-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-inclusion-page/supportProgramsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "description",
      "icon",
      "iconType",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "student-inclusion-page/whoWeSupportSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-life-page/beyondClassroomIntro": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-life-page/committeesSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "description",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "student-life-page/lifeFeature": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-programs-page/highlightsSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-programs-page/houseCaptainsSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-programs-page/objectivesSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-programs-page/tourIntro": {
    "section": [
      "heading"
    ],
    "heading": [
      "accentTitle",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-staff-wellbeing-page/classroomIntegration": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-staff-wellbeing-page/commitment": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-staff-wellbeing-page/counselingSupportSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-staff-wellbeing-page/selSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-staff-wellbeing-page/wellbeingFramework": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "student-staff-wellbeing-page/wellnessCampaigns": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "transportation-safety-page/enrollSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "transportation-safety-page/featuresSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "transportation-safety-page/safetyHighlight": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  }
};

/** Hero fields used per page id. */
export const HERO_FIELDS: Record<string, { hero: string[]; heading: string[] }> = {
  "about-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "eyebrow",
      "title"
    ]
  },
  "academics-elementary-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "academics-high-school-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "eyebrow",
      "title"
    ]
  },
  "academics-kindergarten-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "academics-middle-school-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "eyebrow",
      "title"
    ]
  },
  "academics-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "admissions-application-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "admissions-book-tour-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "admissions-faq-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "admissions-fees-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "admissions-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "admissions-register-interest-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "admissions-withdrawal-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "careers-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "contact-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "extra-curricular-activities-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "food-services-nutrition-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "health-safety-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "homepage-main": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "subtitle",
      "title"
    ]
  },
  "medical-services-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "news-listing-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "our-campus-page": {
    "hero": [
      "heading",
      "image"
    ],
    "heading": [
      "title"
    ]
  },
  "our-community-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "our-team-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "parent-involvement-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "school-calendar-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "school-policies-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "school-reports-page": {
    "hero": [
      "heading",
      "image"
    ],
    "heading": [
      "title"
    ]
  },
  "school-supplies-uniform-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "student-inclusion-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "student-life-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "student-programs-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "student-staff-wellbeing-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "transportation-safety-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  }
};
